version: '3.8'
services:

  # Define Telegraf service
  telegraf:
    image: telegraf
    container_name: telegraf
    environment:
      HOSTNAME: "telegraf"
    # Telegraf requires network access to InfluxDB
    links:
      - influxdb
    volumes:
      # Telegraf configuration is defined in a way that collects the CPU metrics
      - ./telegraf_config/:/etc/telegraf/
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    networks:
      - tick_network

  # Define InfluxDB service
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    networks:
      - tick_network
  
  # Define Chronograf service
  chronograf:
    image: chronograf
    ports:
    - 8888:8888
    command: ["chronograf", "--influxdb-url=http://influxdb:8086", "--kapacitor-url=http://kapacitor:9092"]
    links:
    # Chronograf requires network access to InfluxDB and Kapacitor
    - influxdb
    - kapacitor
    depends_on:
      - influxdb
      - kapacitor
      - telegraf
    networks:
      - tick_network
  
  # Define Kapacitor service
  kapacitor:
    image: kapacitor:1.5.3
    container_name: kapacitor
    environment:
    - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    links:
      - influxdb
    depends_on:
      - influxdb
    networks:
      - tick_network

networks:
  tick_network:
    driver: bridge